SELECT 0 "input", BITCOUNT (0) "bitcount" FROM DUMMY
UNION ALL
SELECT 1, BITCOUNT (1) FROM DUMMY
UNION ALL
SELECT 3, BITCOUNT (3) FROM DUMMY
UNION ALL
SELECT 6, BITCOUNT (6) FROM DUMMY
UNION ALL
SELECT 255, BITCOUNT (255) FROM DUMMY

UNION ALL
SELECT 256, BITCOUNT (256) FROM DUMMY
UNION ALL 
SELECT 257, BITCOUNT (257) FROM DUMMY
UNION ALL 
SELECT 510, BITCOUNT (510) FROM DUMMY;
