-- this syntax is used for testing the standard deviation and variance functions in SAP HANA 

CREATE COLUMN TABLE TESTRESULTS (
	NAME VARCHAR(20),
	SCORE INTEGER
);

INSERT INTO TESTRESULTS VALUES('Gern',8);
INSERT INTO TESTRESULTS VALUES('Ignacita',10);
INSERT INTO TESTRESULTS VALUES('Jamie',4);
INSERT INTO TESTRESULTS VALUES('Smitty',7);
INSERT INTO TESTRESULTS VALUES('Doreen',9);
INSERT INTO TESTRESULTS VALUES('Hazel',7);

SELECT
 VAR_SAMP(SCORE) AS "VAR_SAMP", 
 STDDEV_SAMP(SCORE) AS "STDDEV_SAMP",
 VAR_SAMP(SCORE) AS "VAR",
 STDDEV(SCORE) AS "STDDEV"
FROM TESTRESULTS;

SELECT
 VAR_POP(SCORE) AS "VAR_POP", 
 STDDEV_POP(SCORE) AS "STDDEV_POP"
FROM TESTRESULTS;
